# Generated by Django 3.2 on 2021-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='fecha_creación',
            field=models.CharField(max_length=100),
        ),
    ]
