# Generated by Django 3.2.9 on 2021-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0002_alter_cuadro_fecha_creación'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
