# Generated by Django 3.2.9 on 2021-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0003_cuadro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='imagen',
            field=models.ImageField(default='images/default-image.png', upload_to='images/'),
        ),
    ]
